// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototagscache.proto

#include "prototagscache.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_protoimageinfo_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ProtoImageInfo_protoimageinfo_2eproto;
class ProtoTagsCacheDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ProtoTagsCache> _instance;
} _ProtoTagsCache_default_instance_;
static void InitDefaultsscc_info_ProtoTagsCache_prototagscache_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ProtoTagsCache_default_instance_;
    new (ptr) ::ProtoTagsCache();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtoTagsCache::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ProtoTagsCache_prototagscache_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ProtoTagsCache_prototagscache_2eproto}, {
      &scc_info_ProtoImageInfo_protoimageinfo_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_prototagscache_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_prototagscache_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_prototagscache_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_prototagscache_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtoTagsCache, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ProtoTagsCache, image_info_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ProtoTagsCache)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_ProtoTagsCache_default_instance_),
};

const char descriptor_table_protodef_prototagscache_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024prototagscache.proto\032\024protoimageinfo.p"
  "roto\"5\n\016ProtoTagsCache\022#\n\nimage_info\030\001 \003"
  "(\0132\017.ProtoImageInfob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_prototagscache_2eproto_deps[1] = {
  &::descriptor_table_protoimageinfo_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_prototagscache_2eproto_sccs[1] = {
  &scc_info_ProtoTagsCache_prototagscache_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_prototagscache_2eproto_once;
static bool descriptor_table_prototagscache_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_prototagscache_2eproto = {
  &descriptor_table_prototagscache_2eproto_initialized, descriptor_table_protodef_prototagscache_2eproto, "prototagscache.proto", 107,
  &descriptor_table_prototagscache_2eproto_once, descriptor_table_prototagscache_2eproto_sccs, descriptor_table_prototagscache_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_prototagscache_2eproto::offsets,
  file_level_metadata_prototagscache_2eproto, 1, file_level_enum_descriptors_prototagscache_2eproto, file_level_service_descriptors_prototagscache_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_prototagscache_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_prototagscache_2eproto), true);

// ===================================================================

void ProtoTagsCache::InitAsDefaultInstance() {
}
class ProtoTagsCache::_Internal {
 public:
};

void ProtoTagsCache::clear_image_info() {
  image_info_.Clear();
}
ProtoTagsCache::ProtoTagsCache()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtoTagsCache)
}
ProtoTagsCache::ProtoTagsCache(const ProtoTagsCache& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      image_info_(from.image_info_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ProtoTagsCache)
}

void ProtoTagsCache::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ProtoTagsCache_prototagscache_2eproto.base);
}

ProtoTagsCache::~ProtoTagsCache() {
  // @@protoc_insertion_point(destructor:ProtoTagsCache)
  SharedDtor();
}

void ProtoTagsCache::SharedDtor() {
}

void ProtoTagsCache::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProtoTagsCache& ProtoTagsCache::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ProtoTagsCache_prototagscache_2eproto.base);
  return *internal_default_instance();
}


void ProtoTagsCache::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtoTagsCache)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  image_info_.Clear();
  _internal_metadata_.Clear();
}

const char* ProtoTagsCache::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .ProtoImageInfo image_info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_image_info(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ProtoTagsCache::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtoTagsCache)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ProtoImageInfo image_info = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_image_info_size()); i < n; i++) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(1, this->_internal_image_info(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtoTagsCache)
  return target;
}

size_t ProtoTagsCache::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtoTagsCache)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ProtoImageInfo image_info = 1;
  total_size += 1UL * this->_internal_image_info_size();
  for (const auto& msg : this->image_info_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtoTagsCache::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtoTagsCache)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoTagsCache* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ProtoTagsCache>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtoTagsCache)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtoTagsCache)
    MergeFrom(*source);
  }
}

void ProtoTagsCache::MergeFrom(const ProtoTagsCache& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtoTagsCache)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  image_info_.MergeFrom(from.image_info_);
}

void ProtoTagsCache::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtoTagsCache)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoTagsCache::CopyFrom(const ProtoTagsCache& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtoTagsCache)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoTagsCache::IsInitialized() const {
  return true;
}

void ProtoTagsCache::InternalSwap(ProtoTagsCache* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  image_info_.InternalSwap(&other->image_info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtoTagsCache::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ProtoTagsCache* Arena::CreateMaybeMessage< ::ProtoTagsCache >(Arena* arena) {
  return Arena::CreateInternal< ::ProtoTagsCache >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
